/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AccountMaster'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AccountMaster'));
  } else {
    // Browser globals (root is window)
    if (!root.ClientPortalWebApi) {
      root.ClientPortalWebApi = {};
    }
    root.ClientPortalWebApi.Account = factory(root.ClientPortalWebApi.ApiClient, root.ClientPortalWebApi.AccountMaster);
  }
}(this, function(ApiClient, AccountMaster) {
  'use strict';

  /**
   * The Account model module.
   * @module model/Account
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Account</code>.
   * account information
   * @alias module:model/Account
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Account</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Account} obj Optional instance to populate.
   * @return {module:model/Account} The populated <code>Account</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('accountId'))
        obj.accountId = ApiClient.convertToType(data['accountId'], 'String');
      if (data.hasOwnProperty('accountVan'))
        obj.accountVan = ApiClient.convertToType(data['accountVan'], 'String');
      if (data.hasOwnProperty('accountTitle'))
        obj.accountTitle = ApiClient.convertToType(data['accountTitle'], 'String');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('accountAlias'))
        obj.accountAlias = ApiClient.convertToType(data['accountAlias'], 'String');
      if (data.hasOwnProperty('accountStatus'))
        obj.accountStatus = ApiClient.convertToType(data['accountStatus'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('tradingType'))
        obj.tradingType = ApiClient.convertToType(data['tradingType'], 'String');
      if (data.hasOwnProperty('faclient'))
        obj.faclient = ApiClient.convertToType(data['faclient'], 'Boolean');
      if (data.hasOwnProperty('parent'))
        obj.parent = ApiClient.convertToType(data['parent'], 'String');
      if (data.hasOwnProperty('desc'))
        obj.desc = ApiClient.convertToType(data['desc'], 'String');
      if (data.hasOwnProperty('covestor'))
        obj.covestor = ApiClient.convertToType(data['covestor'], 'Boolean');
      if (data.hasOwnProperty('master'))
        obj.master = AccountMaster.constructFromObject(data['master']);
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} accountId
   */
  exports.prototype.accountId = undefined;

  /**
   * @member {String} accountVan
   */
  exports.prototype.accountVan = undefined;

  /**
   * @member {String} accountTitle
   */
  exports.prototype.accountTitle = undefined;

  /**
   * @member {String} displayName
   */
  exports.prototype.displayName = undefined;

  /**
   * @member {String} accountAlias
   */
  exports.prototype.accountAlias = undefined;

  /**
   * @member {Number} accountStatus
   */
  exports.prototype.accountStatus = undefined;

  /**
   * @member {String} currency
   */
  exports.prototype.currency = undefined;

  /**
   * @member {String} type
   */
  exports.prototype.type = undefined;

  /**
   * @member {String} tradingType
   */
  exports.prototype.tradingType = undefined;

  /**
   * @member {Boolean} faclient
   */
  exports.prototype.faclient = undefined;

  /**
   * @member {String} parent
   */
  exports.prototype.parent = undefined;

  /**
   * @member {String} desc
   */
  exports.prototype.desc = undefined;

  /**
   * @member {Boolean} covestor
   */
  exports.prototype.covestor = undefined;

  /**
   * @member {module:model/AccountMaster} master
   */
  exports.prototype.master = undefined;

  return exports;

}));
