/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AllocationInnerAssetClassLong', 'model/AllocationInnerAssetClassShort'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AllocationInnerAssetClassLong'), require('./AllocationInnerAssetClassShort'));
  } else {
    // Browser globals (root is window)
    if (!root.ClientPortalWebApi) {
      root.ClientPortalWebApi = {};
    }
    root.ClientPortalWebApi.AllocationInnerAssetClass = factory(root.ClientPortalWebApi.ApiClient, root.ClientPortalWebApi.AllocationInnerAssetClassLong, root.ClientPortalWebApi.AllocationInnerAssetClassShort);
  }
}(this, function(ApiClient, AllocationInnerAssetClassLong, AllocationInnerAssetClassShort) {
  'use strict';

  /**
   * The AllocationInnerAssetClass model module.
   * @module model/AllocationInnerAssetClass
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AllocationInnerAssetClass</code>.
   * portfolio allocation by asset class
   * @alias module:model/AllocationInnerAssetClass
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AllocationInnerAssetClass</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllocationInnerAssetClass} obj Optional instance to populate.
   * @return {module:model/AllocationInnerAssetClass} The populated <code>AllocationInnerAssetClass</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('long'))
        obj._long = AllocationInnerAssetClassLong.constructFromObject(data['long']);
      if (data.hasOwnProperty('short'))
        obj._short = AllocationInnerAssetClassShort.constructFromObject(data['short']);
    }
    return obj;
  }

  /**
   * @member {module:model/AllocationInnerAssetClassLong} _long
   */
  exports.prototype._long = undefined;

  /**
   * @member {module:model/AllocationInnerAssetClassShort} _short
   */
  exports.prototype._short = undefined;

  return exports;

}));
