/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ClientPortalWebApi) {
      root.ClientPortalWebApi = {};
    }
    root.ClientPortalWebApi.AllocationInnerSectorLong = factory(root.ClientPortalWebApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The AllocationInnerSectorLong model module.
   * @module model/AllocationInnerSectorLong
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AllocationInnerSectorLong</code>.
   * long positions allocation
   * @alias module:model/AllocationInnerSectorLong
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AllocationInnerSectorLong</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllocationInnerSectorLong} obj Optional instance to populate.
   * @return {module:model/AllocationInnerSectorLong} The populated <code>AllocationInnerSectorLong</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Others'))
        obj.others = ApiClient.convertToType(data['Others'], 'Number');
      if (data.hasOwnProperty('Utilities'))
        obj.utilities = ApiClient.convertToType(data['Utilities'], 'Number');
      if (data.hasOwnProperty('Energy'))
        obj.energy = ApiClient.convertToType(data['Energy'], 'Number');
      if (data.hasOwnProperty('Technology'))
        obj.technology = ApiClient.convertToType(data['Technology'], 'Number');
      if (data.hasOwnProperty('Financial'))
        obj.financial = ApiClient.convertToType(data['Financial'], 'Number');
      if (data.hasOwnProperty('Communications'))
        obj.communications = ApiClient.convertToType(data['Communications'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} others
   */
  exports.prototype.others = undefined;

  /**
   * @member {Number} utilities
   */
  exports.prototype.utilities = undefined;

  /**
   * @member {Number} energy
   */
  exports.prototype.energy = undefined;

  /**
   * @member {Number} technology
   */
  exports.prototype.technology = undefined;

  /**
   * @member {Number} financial
   */
  exports.prototype.financial = undefined;

  /**
   * @member {Number} communications
   */
  exports.prototype.communications = undefined;

  return exports;

}));
