/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ContractRules'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ContractRules'));
  } else {
    // Browser globals (root is window)
    if (!root.ClientPortalWebApi) {
      root.ClientPortalWebApi = {};
    }
    root.ClientPortalWebApi.Contract = factory(root.ClientPortalWebApi.ApiClient, root.ClientPortalWebApi.ContractRules);
  }
}(this, function(ApiClient, ContractRules) {
  'use strict';

  /**
   * The Contract model module.
   * @module model/Contract
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Contract</code>.
   * Contains all details of the contract, including rules you can use when placing orders
   * @alias module:model/Contract
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Contract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Contract} obj Optional instance to populate.
   * @return {module:model/Contract} The populated <code>Contract</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('r_t_h'))
        obj.rTH = ApiClient.convertToType(data['r_t_h'], 'Boolean');
      if (data.hasOwnProperty('con_id'))
        obj.conId = ApiClient.convertToType(data['con_id'], 'String');
      if (data.hasOwnProperty('company_name'))
        obj.companyName = ApiClient.convertToType(data['company_name'], 'String');
      if (data.hasOwnProperty('exchange'))
        obj.exchange = ApiClient.convertToType(data['exchange'], 'String');
      if (data.hasOwnProperty('local_symbol'))
        obj.localSymbol = ApiClient.convertToType(data['local_symbol'], 'String');
      if (data.hasOwnProperty('instrument_type'))
        obj.instrumentType = ApiClient.convertToType(data['instrument_type'], 'String');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('companyName'))
        obj.companyName = ApiClient.convertToType(data['companyName'], 'String');
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('industry'))
        obj.industry = ApiClient.convertToType(data['industry'], 'String');
      if (data.hasOwnProperty('rules'))
        obj.rules = ContractRules.constructFromObject(data['rules']);
    }
    return obj;
  }

  /**
   * true means you can trade outside RTH(regular trading hours)
   * @member {Boolean} rTH
   */
  exports.prototype.rTH = undefined;

  /**
   * same as that in request
   * @member {String} conId
   */
  exports.prototype.conId = undefined;

  /**
   * @member {String} companyName
   */
  exports.prototype.companyName = undefined;

  /**
   * @member {String} exchange
   */
  exports.prototype.exchange = undefined;

  /**
   * for exmple FB
   * @member {String} localSymbol
   */
  exports.prototype.localSymbol = undefined;

  /**
   * for example STK
   * @member {String} instrumentType
   */
  exports.prototype.instrumentType = undefined;

  /**
   * @member {String} currency
   */
  exports.prototype.currency = undefined;

  /**
   * @member {String} companyName
   */
  exports.prototype.companyName = undefined;

  /**
   * @member {String} category
   */
  exports.prototype.category = undefined;

  /**
   * @member {String} industry
   */
  exports.prototype.industry = undefined;

  /**
   * @member {module:model/ContractRules} rules
   */
  exports.prototype.rules = undefined;

  return exports;

}));
