/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ClientPortalWebApi) {
      root.ClientPortalWebApi = {};
    }
    root.ClientPortalWebApi.HistorydataData = factory(root.ClientPortalWebApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The HistorydataData model module.
   * @module model/HistorydataData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>HistorydataData</code>.
   * @alias module:model/HistorydataData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>HistorydataData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HistorydataData} obj Optional instance to populate.
   * @return {module:model/HistorydataData} The populated <code>HistorydataData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('o'))
        obj.o = ApiClient.convertToType(data['o'], 'Number');
      if (data.hasOwnProperty('c'))
        obj.c = ApiClient.convertToType(data['c'], 'Number');
      if (data.hasOwnProperty('h'))
        obj.h = ApiClient.convertToType(data['h'], 'Number');
      if (data.hasOwnProperty('l'))
        obj.l = ApiClient.convertToType(data['l'], 'Number');
      if (data.hasOwnProperty('v'))
        obj.v = ApiClient.convertToType(data['v'], 'Number');
      if (data.hasOwnProperty('t'))
        obj.t = ApiClient.convertToType(data['t'], 'Number');
    }
    return obj;
  }

  /**
   * open price
   * @member {Number} o
   */
  exports.prototype.o = undefined;

  /**
   * close price
   * @member {Number} c
   */
  exports.prototype.c = undefined;

  /**
   * high price
   * @member {Number} h
   */
  exports.prototype.h = undefined;

  /**
   * low price
   * @member {Number} l
   */
  exports.prototype.l = undefined;

  /**
   * volume
   * @member {Number} v
   */
  exports.prototype.v = undefined;

  /**
   * unix time stamp
   * @member {Number} t
   */
  exports.prototype.t = undefined;

  return exports;

}));
