/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2009Locations'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2009Locations'));
  } else {
    // Browser globals (root is window)
    if (!root.ClientPortalWebApi) {
      root.ClientPortalWebApi = {};
    }
    root.ClientPortalWebApi.InlineResponse2009LocationTree = factory(root.ClientPortalWebApi.ApiClient, root.ClientPortalWebApi.InlineResponse2009Locations);
  }
}(this, function(ApiClient, InlineResponse2009Locations) {
  'use strict';

  /**
   * The InlineResponse2009LocationTree model module.
   * @module model/InlineResponse2009LocationTree
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>InlineResponse2009LocationTree</code>.
   * @alias module:model/InlineResponse2009LocationTree
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>InlineResponse2009LocationTree</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2009LocationTree} obj Optional instance to populate.
   * @return {module:model/InlineResponse2009LocationTree} The populated <code>InlineResponse2009LocationTree</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('display_name'))
        obj.displayName = ApiClient.convertToType(data['display_name'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('locations'))
        obj.locations = ApiClient.convertToType(data['locations'], [InlineResponse2009Locations]);
    }
    return obj;
  }

  /**
   * @member {String} displayName
   */
  exports.prototype.displayName = undefined;

  /**
   * @member {String} type
   */
  exports.prototype.type = undefined;

  /**
   * @member {Array.<module:model/InlineResponse2009Locations>} locations
   */
  exports.prototype.locations = undefined;

  return exports;

}));
