/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ClientPortalWebApi) {
      root.ClientPortalWebApi = {};
    }
    root.ClientPortalWebApi.Ledger = factory(root.ClientPortalWebApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Ledger model module.
   * @module model/Ledger
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Ledger</code>.
   * @alias module:model/Ledger
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Ledger</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ledger} obj Optional instance to populate.
   * @return {module:model/Ledger} The populated <code>Ledger</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('commoditymarketvalue'))
        obj.commoditymarketvalue = ApiClient.convertToType(data['commoditymarketvalue'], 'Number');
      if (data.hasOwnProperty('futuremarketvalue'))
        obj.futuremarketvalue = ApiClient.convertToType(data['futuremarketvalue'], 'Number');
      if (data.hasOwnProperty('settledcash'))
        obj.settledcash = ApiClient.convertToType(data['settledcash'], 'Number');
      if (data.hasOwnProperty('exchangerate'))
        obj.exchangerate = ApiClient.convertToType(data['exchangerate'], 'Number');
      if (data.hasOwnProperty('sessionid'))
        obj.sessionid = ApiClient.convertToType(data['sessionid'], 'Number');
      if (data.hasOwnProperty('cashbalance'))
        obj.cashbalance = ApiClient.convertToType(data['cashbalance'], 'Number');
      if (data.hasOwnProperty('corporatebondsmarketvalue'))
        obj.corporatebondsmarketvalue = ApiClient.convertToType(data['corporatebondsmarketvalue'], 'Number');
      if (data.hasOwnProperty('warrantsmarketvalue'))
        obj.warrantsmarketvalue = ApiClient.convertToType(data['warrantsmarketvalue'], 'Number');
      if (data.hasOwnProperty('netliquidationvalue'))
        obj.netliquidationvalue = ApiClient.convertToType(data['netliquidationvalue'], 'Number');
      if (data.hasOwnProperty('interest'))
        obj.interest = ApiClient.convertToType(data['interest'], 'Number');
      if (data.hasOwnProperty('unrealizedpnl'))
        obj.unrealizedpnl = ApiClient.convertToType(data['unrealizedpnl'], 'Number');
      if (data.hasOwnProperty('stockmarketvalue'))
        obj.stockmarketvalue = ApiClient.convertToType(data['stockmarketvalue'], 'Number');
      if (data.hasOwnProperty('moneyfunds'))
        obj.moneyfunds = ApiClient.convertToType(data['moneyfunds'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('realizedpnl'))
        obj.realizedpnl = ApiClient.convertToType(data['realizedpnl'], 'Number');
      if (data.hasOwnProperty('funds'))
        obj.funds = ApiClient.convertToType(data['funds'], 'Number');
      if (data.hasOwnProperty('acctcode'))
        obj.acctcode = ApiClient.convertToType(data['acctcode'], 'String');
      if (data.hasOwnProperty('issueroptionsmarketvalue'))
        obj.issueroptionsmarketvalue = ApiClient.convertToType(data['issueroptionsmarketvalue'], 'Number');
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'Number');
      if (data.hasOwnProperty('severity'))
        obj.severity = ApiClient.convertToType(data['severity'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} commoditymarketvalue
   */
  exports.prototype.commoditymarketvalue = undefined;

  /**
   * @member {Number} futuremarketvalue
   */
  exports.prototype.futuremarketvalue = undefined;

  /**
   * @member {Number} settledcash
   */
  exports.prototype.settledcash = undefined;

  /**
   * @member {Number} exchangerate
   */
  exports.prototype.exchangerate = undefined;

  /**
   * @member {Number} sessionid
   */
  exports.prototype.sessionid = undefined;

  /**
   * @member {Number} cashbalance
   */
  exports.prototype.cashbalance = undefined;

  /**
   * @member {Number} corporatebondsmarketvalue
   */
  exports.prototype.corporatebondsmarketvalue = undefined;

  /**
   * @member {Number} warrantsmarketvalue
   */
  exports.prototype.warrantsmarketvalue = undefined;

  /**
   * @member {Number} netliquidationvalue
   */
  exports.prototype.netliquidationvalue = undefined;

  /**
   * @member {Number} interest
   */
  exports.prototype.interest = undefined;

  /**
   * @member {Number} unrealizedpnl
   */
  exports.prototype.unrealizedpnl = undefined;

  /**
   * @member {Number} stockmarketvalue
   */
  exports.prototype.stockmarketvalue = undefined;

  /**
   * @member {Number} moneyfunds
   */
  exports.prototype.moneyfunds = undefined;

  /**
   * @member {String} currency
   */
  exports.prototype.currency = undefined;

  /**
   * @member {Number} realizedpnl
   */
  exports.prototype.realizedpnl = undefined;

  /**
   * @member {Number} funds
   */
  exports.prototype.funds = undefined;

  /**
   * @member {String} acctcode
   */
  exports.prototype.acctcode = undefined;

  /**
   * @member {Number} issueroptionsmarketvalue
   */
  exports.prototype.issueroptionsmarketvalue = undefined;

  /**
   * @member {String} key
   */
  exports.prototype.key = undefined;

  /**
   * @member {Number} timestamp
   */
  exports.prototype.timestamp = undefined;

  /**
   * @member {Number} severity
   */
  exports.prototype.severity = undefined;

  return exports;

}));
