/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ClientPortalWebApi) {
      root.ClientPortalWebApi = {};
    }
    root.ClientPortalWebApi.Order = factory(root.ClientPortalWebApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Order model module.
   * @module model/Order
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Order</code>.
   * contains all the order related info
   * @alias module:model/Order
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Order} obj Optional instance to populate.
   * @return {module:model/Order} The populated <code>Order</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('acct'))
        obj.acct = ApiClient.convertToType(data['acct'], 'String');
      if (data.hasOwnProperty('conid'))
        obj.conid = ApiClient.convertToType(data['conid'], 'Number');
      if (data.hasOwnProperty('orderDesc'))
        obj.orderDesc = ApiClient.convertToType(data['orderDesc'], 'String');
      if (data.hasOwnProperty('description1'))
        obj.description1 = ApiClient.convertToType(data['description1'], 'String');
      if (data.hasOwnProperty('ticker'))
        obj.ticker = ApiClient.convertToType(data['ticker'], 'String');
      if (data.hasOwnProperty('secType'))
        obj.secType = ApiClient.convertToType(data['secType'], 'String');
      if (data.hasOwnProperty('listingExchange'))
        obj.listingExchange = ApiClient.convertToType(data['listingExchange'], 'String');
      if (data.hasOwnProperty('remainingQuantity'))
        obj.remainingQuantity = ApiClient.convertToType(data['remainingQuantity'], 'String');
      if (data.hasOwnProperty('filledQuantity'))
        obj.filledQuantity = ApiClient.convertToType(data['filledQuantity'], 'String');
      if (data.hasOwnProperty('companyName'))
        obj.companyName = ApiClient.convertToType(data['companyName'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('origOrderType'))
        obj.origOrderType = ApiClient.convertToType(data['origOrderType'], 'String');
      if (data.hasOwnProperty('side'))
        obj.side = ApiClient.convertToType(data['side'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('bgColor'))
        obj.bgColor = ApiClient.convertToType(data['bgColor'], 'String');
      if (data.hasOwnProperty('fgColor'))
        obj.fgColor = ApiClient.convertToType(data['fgColor'], 'String');
      if (data.hasOwnProperty('orderId'))
        obj.orderId = ApiClient.convertToType(data['orderId'], 'Number');
      if (data.hasOwnProperty('parentId'))
        obj.parentId = ApiClient.convertToType(data['parentId'], 'Number');
    }
    return obj;
  }

  /**
   * account id
   * @member {String} acct
   */
  exports.prototype.acct = undefined;

  /**
   * @member {Number} conid
   */
  exports.prototype.conid = undefined;

  /**
   * @member {String} orderDesc
   */
  exports.prototype.orderDesc = undefined;

  /**
   * @member {String} description1
   */
  exports.prototype.description1 = undefined;

  /**
   * for exmple FB
   * @member {String} ticker
   */
  exports.prototype.ticker = undefined;

  /**
   * for example STK
   * @member {String} secType
   */
  exports.prototype.secType = undefined;

  /**
   * for example NASDAQ.NMS
   * @member {String} listingExchange
   */
  exports.prototype.listingExchange = undefined;

  /**
   * @member {String} remainingQuantity
   */
  exports.prototype.remainingQuantity = undefined;

  /**
   * @member {String} filledQuantity
   */
  exports.prototype.filledQuantity = undefined;

  /**
   * @member {String} companyName
   */
  exports.prototype.companyName = undefined;

  /**
   * PendingSubmit - Indicates the order was sent, but confirmation has not been received that it has been received by the destination.                  Occurs most commonly if an exchange is closed. PendingCancel - Indicates that a request has been sent to cancel an order but confirmation has not been received of its cancellation. PreSubmitted - Indicates that a simulated order type has been accepted by the IBKR system and that this order has yet to be elected.                 The order is held in the IBKR system until the election criteria are met. At that time the order is transmitted to the order destination as specified.  Submitted - Indicates that the order has been accepted at the order destination and is working. Cancelled - Indicates that the balance of the order has been confirmed cancelled by the IB system.              This could occur unexpectedly when IB or the destination has rejected the order.   Filled - Indicates that the order has been completely filled.  Inactive - Indicates the order is not working, for instance if the order was invalid and triggered an error message,            or if the order was to short a security and shares have not yet been located.  
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * for example Limit
   * @member {String} origOrderType
   */
  exports.prototype.origOrderType = undefined;

  /**
   * BUY or SELL
   * @member {String} side
   */
  exports.prototype.side = undefined;

  /**
   * @member {Number} price
   */
  exports.prototype.price = undefined;

  /**
   * back-ground color
   * @member {String} bgColor
   */
  exports.prototype.bgColor = undefined;

  /**
   * @member {String} fgColor
   */
  exports.prototype.fgColor = undefined;

  /**
   * @member {Number} orderId
   */
  exports.prototype.orderId = undefined;

  /**
   * Only exists in child order of bracket
   * @member {Number} parentId
   */
  exports.prototype.parentId = undefined;

  return exports;

}));
