/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ClientPortalWebApi) {
      root.ClientPortalWebApi = {};
    }
    root.ClientPortalWebApi.PositionInner = factory(root.ClientPortalWebApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The PositionInner model module.
   * @module model/PositionInner
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PositionInner</code>.
   * Account Information
   * @alias module:model/PositionInner
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PositionInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PositionInner} obj Optional instance to populate.
   * @return {module:model/PositionInner} The populated <code>PositionInner</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('acctId'))
        obj.acctId = ApiClient.convertToType(data['acctId'], 'String');
      if (data.hasOwnProperty('conid'))
        obj.conid = ApiClient.convertToType(data['conid'], 'Number');
      if (data.hasOwnProperty('contractDesc'))
        obj.contractDesc = ApiClient.convertToType(data['contractDesc'], 'String');
      if (data.hasOwnProperty('assetClass'))
        obj.assetClass = ApiClient.convertToType(data['assetClass'], 'String');
      if (data.hasOwnProperty('position'))
        obj.position = ApiClient.convertToType(data['position'], 'Number');
      if (data.hasOwnProperty('mktPrice'))
        obj.mktPrice = ApiClient.convertToType(data['mktPrice'], 'Number');
      if (data.hasOwnProperty('mktValue'))
        obj.mktValue = ApiClient.convertToType(data['mktValue'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('avgCost'))
        obj.avgCost = ApiClient.convertToType(data['avgCost'], 'Number');
      if (data.hasOwnProperty('avgPrice'))
        obj.avgPrice = ApiClient.convertToType(data['avgPrice'], 'Number');
      if (data.hasOwnProperty('realizedPnl'))
        obj.realizedPnl = ApiClient.convertToType(data['realizedPnl'], 'Number');
      if (data.hasOwnProperty('unrealizedPnl'))
        obj.unrealizedPnl = ApiClient.convertToType(data['unrealizedPnl'], 'Number');
      if (data.hasOwnProperty('exchs'))
        obj.exchs = ApiClient.convertToType(data['exchs'], 'String');
      if (data.hasOwnProperty('expiry'))
        obj.expiry = ApiClient.convertToType(data['expiry'], 'String');
      if (data.hasOwnProperty('putOrCall'))
        obj.putOrCall = ApiClient.convertToType(data['putOrCall'], 'String');
      if (data.hasOwnProperty('multiplier'))
        obj.multiplier = ApiClient.convertToType(data['multiplier'], 'Number');
      if (data.hasOwnProperty('strike'))
        obj.strike = ApiClient.convertToType(data['strike'], 'Number');
      if (data.hasOwnProperty('exerciseStyle'))
        obj.exerciseStyle = ApiClient.convertToType(data['exerciseStyle'], 'String');
      if (data.hasOwnProperty('undConid'))
        obj.undConid = ApiClient.convertToType(data['undConid'], 'Number');
      if (data.hasOwnProperty('conExchMap'))
        obj.conExchMap = ApiClient.convertToType(data['conExchMap'], ['String']);
      if (data.hasOwnProperty('baseMktValue'))
        obj.baseMktValue = ApiClient.convertToType(data['baseMktValue'], 'Number');
      if (data.hasOwnProperty('baseMktPrice'))
        obj.baseMktPrice = ApiClient.convertToType(data['baseMktPrice'], 'Number');
      if (data.hasOwnProperty('baseAvgCost'))
        obj.baseAvgCost = ApiClient.convertToType(data['baseAvgCost'], 'Number');
      if (data.hasOwnProperty('baseAvgPrice'))
        obj.baseAvgPrice = ApiClient.convertToType(data['baseAvgPrice'], 'Number');
      if (data.hasOwnProperty('baseRealizedPnl'))
        obj.baseRealizedPnl = ApiClient.convertToType(data['baseRealizedPnl'], 'Number');
      if (data.hasOwnProperty('baseUnrealizedPnl'))
        obj.baseUnrealizedPnl = ApiClient.convertToType(data['baseUnrealizedPnl'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('lastTradingDay'))
        obj.lastTradingDay = ApiClient.convertToType(data['lastTradingDay'], 'String');
      if (data.hasOwnProperty('group'))
        obj.group = ApiClient.convertToType(data['group'], 'String');
      if (data.hasOwnProperty('sector'))
        obj.sector = ApiClient.convertToType(data['sector'], 'String');
      if (data.hasOwnProperty('sectorGroup'))
        obj.sectorGroup = ApiClient.convertToType(data['sectorGroup'], 'String');
      if (data.hasOwnProperty('ticker'))
        obj.ticker = ApiClient.convertToType(data['ticker'], 'String');
      if (data.hasOwnProperty('undComp'))
        obj.undComp = ApiClient.convertToType(data['undComp'], 'String');
      if (data.hasOwnProperty('undSym'))
        obj.undSym = ApiClient.convertToType(data['undSym'], 'String');
      if (data.hasOwnProperty('fullName'))
        obj.fullName = ApiClient.convertToType(data['fullName'], 'String');
      if (data.hasOwnProperty('pageSize'))
        obj.pageSize = ApiClient.convertToType(data['pageSize'], 'Number');
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} acctId
   */
  exports.prototype.acctId = undefined;

  /**
   * @member {Number} conid
   */
  exports.prototype.conid = undefined;

  /**
   * @member {String} contractDesc
   */
  exports.prototype.contractDesc = undefined;

  /**
   * @member {String} assetClass
   */
  exports.prototype.assetClass = undefined;

  /**
   * @member {Number} position
   */
  exports.prototype.position = undefined;

  /**
   * @member {Number} mktPrice
   */
  exports.prototype.mktPrice = undefined;

  /**
   * @member {Number} mktValue
   */
  exports.prototype.mktValue = undefined;

  /**
   * @member {String} currency
   */
  exports.prototype.currency = undefined;

  /**
   * @member {Number} avgCost
   */
  exports.prototype.avgCost = undefined;

  /**
   * @member {Number} avgPrice
   */
  exports.prototype.avgPrice = undefined;

  /**
   * @member {Number} realizedPnl
   */
  exports.prototype.realizedPnl = undefined;

  /**
   * @member {Number} unrealizedPnl
   */
  exports.prototype.unrealizedPnl = undefined;

  /**
   * @member {String} exchs
   */
  exports.prototype.exchs = undefined;

  /**
   * @member {String} expiry
   */
  exports.prototype.expiry = undefined;

  /**
   * @member {String} putOrCall
   */
  exports.prototype.putOrCall = undefined;

  /**
   * @member {Number} multiplier
   */
  exports.prototype.multiplier = undefined;

  /**
   * @member {Number} strike
   */
  exports.prototype.strike = undefined;

  /**
   * @member {String} exerciseStyle
   */
  exports.prototype.exerciseStyle = undefined;

  /**
   * @member {Number} undConid
   */
  exports.prototype.undConid = undefined;

  /**
   * @member {Array.<String>} conExchMap
   */
  exports.prototype.conExchMap = undefined;

  /**
   * @member {Number} baseMktValue
   */
  exports.prototype.baseMktValue = undefined;

  /**
   * @member {Number} baseMktPrice
   */
  exports.prototype.baseMktPrice = undefined;

  /**
   * @member {Number} baseAvgCost
   */
  exports.prototype.baseAvgCost = undefined;

  /**
   * @member {Number} baseAvgPrice
   */
  exports.prototype.baseAvgPrice = undefined;

  /**
   * @member {Number} baseRealizedPnl
   */
  exports.prototype.baseRealizedPnl = undefined;

  /**
   * @member {Number} baseUnrealizedPnl
   */
  exports.prototype.baseUnrealizedPnl = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} lastTradingDay
   */
  exports.prototype.lastTradingDay = undefined;

  /**
   * @member {String} group
   */
  exports.prototype.group = undefined;

  /**
   * @member {String} sector
   */
  exports.prototype.sector = undefined;

  /**
   * @member {String} sectorGroup
   */
  exports.prototype.sectorGroup = undefined;

  /**
   * @member {String} ticker
   */
  exports.prototype.ticker = undefined;

  /**
   * @member {String} undComp
   */
  exports.prototype.undComp = undefined;

  /**
   * @member {String} undSym
   */
  exports.prototype.undSym = undefined;

  /**
   * @member {String} fullName
   */
  exports.prototype.fullName = undefined;

  /**
   * @member {Number} pageSize
   */
  exports.prototype.pageSize = undefined;

  /**
   * @member {String} model
   */
  exports.prototype.model = undefined;

  return exports;

}));
