/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ScannerparamsFilter'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ScannerparamsFilter'));
  } else {
    // Browser globals (root is window)
    if (!root.ClientPortalWebApi) {
      root.ClientPortalWebApi = {};
    }
    root.ClientPortalWebApi.ScannerParams = factory(root.ClientPortalWebApi.ApiClient, root.ClientPortalWebApi.ScannerparamsFilter);
  }
}(this, function(ApiClient, ScannerparamsFilter) {
  'use strict';

  /**
   * The ScannerParams model module.
   * @module model/ScannerParams
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ScannerParams</code>.
   * @alias module:model/ScannerParams
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ScannerParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ScannerParams} obj Optional instance to populate.
   * @return {module:model/ScannerParams} The populated <code>ScannerParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('instrument'))
        obj.instrument = ApiClient.convertToType(data['instrument'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('filter'))
        obj.filter = ApiClient.convertToType(data['filter'], [ScannerparamsFilter]);
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('size'))
        obj.size = ApiClient.convertToType(data['size'], 'String');
    }
    return obj;
  }

  /**
   * for example-STK
   * @member {String} instrument
   */
  exports.prototype.instrument = undefined;

  /**
   * for example-TOP_PERC_GAIN
   * @member {String} type
   */
  exports.prototype.type = undefined;

  /**
   * @member {Array.<module:model/ScannerparamsFilter>} filter
   */
  exports.prototype.filter = undefined;

  /**
   * @member {String} location
   */
  exports.prototype.location = undefined;

  /**
   * @member {String} size
   */
  exports.prototype.size = undefined;

  return exports;

}));
