/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ClientPortalWebApi) {
      root.ClientPortalWebApi = {};
    }
    root.ClientPortalWebApi.SummaryExcludedAccounts = factory(root.ClientPortalWebApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The SummaryExcludedAccounts model module.
   * @module model/SummaryExcludedAccounts
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SummaryExcludedAccounts</code>.
   * @alias module:model/SummaryExcludedAccounts
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SummaryExcludedAccounts</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SummaryExcludedAccounts} obj Optional instance to populate.
   * @return {module:model/SummaryExcludedAccounts} The populated <code>SummaryExcludedAccounts</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('lastUpdateAttempt'))
        obj.lastUpdateAttempt = ApiClient.convertToType(data['lastUpdateAttempt'], 'String');
      if (data.hasOwnProperty('fiName'))
        obj.fiName = ApiClient.convertToType(data['fiName'], 'String');
      if (data.hasOwnProperty('acctTitle'))
        obj.acctTitle = ApiClient.convertToType(data['acctTitle'], 'String');
      if (data.hasOwnProperty('acctNumAtFI'))
        obj.acctNumAtFI = ApiClient.convertToType(data['acctNumAtFI'], 'String');
      if (data.hasOwnProperty('acctId'))
        obj.acctId = ApiClient.convertToType(data['acctId'], 'String');
      if (data.hasOwnProperty('lastUpdate'))
        obj.lastUpdate = ApiClient.convertToType(data['lastUpdate'], 'String');
      if (data.hasOwnProperty('harvestCode'))
        obj.harvestCode = ApiClient.convertToType(data['harvestCode'], 'Number');
      if (data.hasOwnProperty('lastUpdateStatusCode'))
        obj.lastUpdateStatusCode = ApiClient.convertToType(data['lastUpdateStatusCode'], 'String');
      if (data.hasOwnProperty('rc'))
        obj.rc = ApiClient.convertToType(data['rc'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} lastUpdateAttempt
   */
  exports.prototype.lastUpdateAttempt = undefined;

  /**
   * @member {String} fiName
   */
  exports.prototype.fiName = undefined;

  /**
   * @member {String} acctTitle
   */
  exports.prototype.acctTitle = undefined;

  /**
   * @member {String} acctNumAtFI
   */
  exports.prototype.acctNumAtFI = undefined;

  /**
   * @member {String} acctId
   */
  exports.prototype.acctId = undefined;

  /**
   * @member {String} lastUpdate
   */
  exports.prototype.lastUpdate = undefined;

  /**
   * @member {Number} harvestCode
   */
  exports.prototype.harvestCode = undefined;

  /**
   * @member {String} lastUpdateStatusCode
   */
  exports.prototype.lastUpdateStatusCode = undefined;

  /**
   * @member {Number} rc
   */
  exports.prototype.rc = undefined;

  return exports;

}));
