/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse20017'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InlineResponse20017'));
  } else {
    // Browser globals (root is window)
    if (!root.ClientPortalWebApi) {
      root.ClientPortalWebApi = {};
    }
    root.ClientPortalWebApi.IBCustApi = factory(root.ClientPortalWebApi.ApiClient, root.ClientPortalWebApi.InlineResponse20017);
  }
}(this, function(ApiClient, InlineResponse20017) {
  'use strict';

  /**
   * IBCust service.
   * @module api/IBCustApi
   * @version 1.0.0
   */

  /**
   * Constructs a new IBCustApi. 
   * @alias module:api/IBCustApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the ibcustEntityInfoGet operation.
     * @callback module:api/IBCustApi~ibcustEntityInfoGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/InlineResponse20017>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * IBCust Entity Info
     * Returns Applicant Id with all owner related entities
     * @param {module:api/IBCustApi~ibcustEntityInfoGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/InlineResponse20017>}
     */
    this.ibcustEntityInfoGet = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [InlineResponse20017];

      return this.apiClient.callApi(
        '/ibcust/entity/info', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
