/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Body3', 'model/Body4', 'model/Performance', 'model/Summary'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Body3'), require('../model/Body4'), require('../model/Performance'), require('../model/Summary'));
  } else {
    // Browser globals (root is window)
    if (!root.ClientPortalWebApi) {
      root.ClientPortalWebApi = {};
    }
    root.ClientPortalWebApi.PortfolioAnalystApi = factory(root.ClientPortalWebApi.ApiClient, root.ClientPortalWebApi.Body3, root.ClientPortalWebApi.Body4, root.ClientPortalWebApi.Performance, root.ClientPortalWebApi.Summary);
  }
}(this, function(ApiClient, Body3, Body4, Performance, Summary) {
  'use strict';

  /**
   * PortfolioAnalyst service.
   * @module api/PortfolioAnalystApi
   * @version 1.0.0
   */

  /**
   * Constructs a new PortfolioAnalystApi. 
   * @alias module:api/PortfolioAnalystApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the paPerformancePost operation.
     * @callback module:api/PortfolioAnalystApi~paPerformancePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Performance} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Account Performance
     * Returns the performance (MTM) for the given accounts, if more than one account is passed, the result is consolidated.
     * @param {module:model/Body3} body an array of account ids
     * @param {module:api/PortfolioAnalystApi~paPerformancePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Performance}
     */
    this.paPerformancePost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling paPerformancePost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Performance;

      return this.apiClient.callApi(
        '/pa/performance', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the paSummaryPost operation.
     * @callback module:api/PortfolioAnalystApi~paSummaryPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Summary} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Account Balance's Summary
     * Returns a summary of all account balances for the given accounts, if more than one account is passed, the result is consolidated.
     * @param {module:model/Body4} body an array of account ids
     * @param {module:api/PortfolioAnalystApi~paSummaryPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Summary}
     */
    this.paSummaryPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling paSummaryPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Summary;

      return this.apiClient.callApi(
        '/pa/summary', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
