/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ClientPortalWebApi);
  }
}(this, function(expect, ClientPortalWebApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AllocationInnerSectorLong', function() {
      beforeEach(function() {
        instance = new ClientPortalWebApi.AllocationInnerSectorLong();
      });

      it('should create an instance of AllocationInnerSectorLong', function() {
        // TODO: update the code to test AllocationInnerSectorLong
        expect(instance).to.be.a(ClientPortalWebApi.AllocationInnerSectorLong);
      });

      it('should have the property others (base name: "Others")', function() {
        // TODO: update the code to test the property others
        expect(instance).to.have.property('others');
        // expect(instance.others).to.be(expectedValueLiteral);
      });

      it('should have the property utilities (base name: "Utilities")', function() {
        // TODO: update the code to test the property utilities
        expect(instance).to.have.property('utilities');
        // expect(instance.utilities).to.be(expectedValueLiteral);
      });

      it('should have the property energy (base name: "Energy")', function() {
        // TODO: update the code to test the property energy
        expect(instance).to.have.property('energy');
        // expect(instance.energy).to.be(expectedValueLiteral);
      });

      it('should have the property technology (base name: "Technology")', function() {
        // TODO: update the code to test the property technology
        expect(instance).to.have.property('technology');
        // expect(instance.technology).to.be(expectedValueLiteral);
      });

      it('should have the property financial (base name: "Financial")', function() {
        // TODO: update the code to test the property financial
        expect(instance).to.have.property('financial');
        // expect(instance.financial).to.be(expectedValueLiteral);
      });

      it('should have the property communications (base name: "Communications")', function() {
        // TODO: update the code to test the property communications
        expect(instance).to.have.property('communications');
        // expect(instance.communications).to.be(expectedValueLiteral);
      });

    });
  });

}));
