/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ClientPortalWebApi);
  }
}(this, function(expect, ClientPortalWebApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('IbcustentityinfoEntities', function() {
      beforeEach(function() {
        instance = new ClientPortalWebApi.IbcustentityinfoEntities();
      });

      it('should create an instance of IbcustentityinfoEntities', function() {
        // TODO: update the code to test IbcustentityinfoEntities
        expect(instance).to.be.a(ClientPortalWebApi.IbcustentityinfoEntities);
      });

      it('should have the property canTrade (base name: "canTrade")', function() {
        // TODO: update the code to test the property canTrade
        expect(instance).to.have.property('canTrade');
        // expect(instance.canTrade).to.be(expectedValueLiteral);
      });

      it('should have the property canSign (base name: "canSign")', function() {
        // TODO: update the code to test the property canSign
        expect(instance).to.have.property('canSign');
        // expect(instance.canSign).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property address (base name: "address")', function() {
        // TODO: update the code to test the property address
        expect(instance).to.have.property('address');
        // expect(instance.address).to.be(expectedValueLiteral);
      });

      it('should have the property identDocs (base name: "identDocs")', function() {
        // TODO: update the code to test the property identDocs
        expect(instance).to.have.property('identDocs');
        // expect(instance.identDocs).to.be(expectedValueLiteral);
      });

    });
  });

}));
