/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ClientPortalWebApi);
  }
}(this, function(expect, ClientPortalWebApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse20021', function() {
      beforeEach(function() {
        instance = new ClientPortalWebApi.InlineResponse20021();
      });

      it('should create an instance of InlineResponse20021', function() {
        // TODO: update the code to test InlineResponse20021
        expect(instance).to.be.a(ClientPortalWebApi.InlineResponse20021);
      });

      it('should have the property T (base name: "T")', function() {
        // TODO: update the code to test the property T
        expect(instance).to.have.property('T');
        // expect(instance.T).to.be(expectedValueLiteral);
      });

      it('should have the property V (base name: "V")', function() {
        // TODO: update the code to test the property V
        expect(instance).to.have.property('V');
        // expect(instance.V).to.be(expectedValueLiteral);
      });

    });
  });

}));
