/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ClientPortalWebApi);
  }
}(this, function(expect, ClientPortalWebApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2009ScanTypeList', function() {
      beforeEach(function() {
        instance = new ClientPortalWebApi.InlineResponse2009ScanTypeList();
      });

      it('should create an instance of InlineResponse2009ScanTypeList', function() {
        // TODO: update the code to test InlineResponse2009ScanTypeList
        expect(instance).to.be.a(ClientPortalWebApi.InlineResponse2009ScanTypeList);
      });

      it('should have the property displayName (base name: "display_name")', function() {
        // TODO: update the code to test the property displayName
        expect(instance).to.have.property('displayName');
        // expect(instance.displayName).to.be(expectedValueLiteral);
      });

      it('should have the property code (base name: "code")', function() {
        // TODO: update the code to test the property code
        expect(instance).to.have.property('code');
        // expect(instance.code).to.be(expectedValueLiteral);
      });

      it('should have the property instruments (base name: "instruments")', function() {
        // TODO: update the code to test the property instruments
        expect(instance).to.have.property('instruments');
        // expect(instance.instruments).to.be(expectedValueLiteral);
      });

    });
  });

}));
