/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ClientPortalWebApi);
  }
}(this, function(expect, ClientPortalWebApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2006', function() {
      beforeEach(function() {
        instance = new ClientPortalWebApi.InlineResponse2006();
      });

      it('should create an instance of InlineResponse2006', function() {
        // TODO: update the code to test InlineResponse2006
        expect(instance).to.be.a(ClientPortalWebApi.InlineResponse2006);
      });

      it('should have the property orderId (base name: "order_id")', function() {
        // TODO: update the code to test the property orderId
        expect(instance).to.have.property('orderId');
        // expect(instance.orderId).to.be(expectedValueLiteral);
      });

      it('should have the property localOrderId (base name: "local_order_id")', function() {
        // TODO: update the code to test the property localOrderId
        expect(instance).to.have.property('localOrderId');
        // expect(instance.localOrderId).to.be(expectedValueLiteral);
      });

      it('should have the property orderStatus (base name: "order_status")', function() {
        // TODO: update the code to test the property orderStatus
        expect(instance).to.have.property('orderStatus');
        // expect(instance.orderStatus).to.be(expectedValueLiteral);
      });

    });
  });

}));
