/*
 * Client Portal Web API
 * Production version of the Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ClientPortalWebApi);
  }
}(this, function(expect, ClientPortalWebApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SummaryAccountSummaries', function() {
      beforeEach(function() {
        instance = new ClientPortalWebApi.SummaryAccountSummaries();
      });

      it('should create an instance of SummaryAccountSummaries', function() {
        // TODO: update the code to test SummaryAccountSummaries
        expect(instance).to.be.a(ClientPortalWebApi.SummaryAccountSummaries);
      });

      it('should have the property chg (base name: "chg")', function() {
        // TODO: update the code to test the property chg
        expect(instance).to.have.property('chg');
        // expect(instance.chg).to.be(expectedValueLiteral);
      });

      it('should have the property hasAccounts (base name: "hasAccounts")', function() {
        // TODO: update the code to test the property hasAccounts
        expect(instance).to.have.property('hasAccounts');
        // expect(instance.hasAccounts).to.be(expectedValueLiteral);
      });

      it('should have the property accountTypeName (base name: "accountTypeName")', function() {
        // TODO: update the code to test the property accountTypeName
        expect(instance).to.have.property('accountTypeName');
        // expect(instance.accountTypeName).to.be(expectedValueLiteral);
      });

      it('should have the property rtn (base name: "rtn")', function() {
        // TODO: update the code to test the property rtn
        expect(instance).to.have.property('rtn');
        // expect(instance.rtn).to.be(expectedValueLiteral);
      });

      it('should have the property endVal (base name: "endVal")', function() {
        // TODO: update the code to test the property endVal
        expect(instance).to.have.property('endVal');
        // expect(instance.endVal).to.be(expectedValueLiteral);
      });

      it('should have the property accountTypeCode (base name: "accountTypeCode")', function() {
        // TODO: update the code to test the property accountTypeCode
        expect(instance).to.have.property('accountTypeCode');
        // expect(instance.accountTypeCode).to.be(expectedValueLiteral);
      });

      it('should have the property startVal (base name: "startVal")', function() {
        // TODO: update the code to test the property startVal
        expect(instance).to.have.property('startVal');
        // expect(instance.startVal).to.be(expectedValueLiteral);
      });

    });
  });

}));
